# -*- coding: utf-8 -*-
"""Beautiful_website.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWTde2zszjj6noU9BZd0TO7dGEP5r48A
"""



"""# Task
Create a static portfolio website for 'Beau Rance Thompson' by generating an `index.html` file with a semantic structure and a `styles.css` file that implements a clean, minimal aesthetic with full-width images and small sans-serif typography. Additionally, create a Python script using the `boto3` library to automate the deployment of these files to an AWS S3 bucket configured for static website hosting.

## Create HTML Structure

### Subtask:
Generate the `index.html` file with a semantic structure tailored for a portfolio.
"""

# Old preview cell cleared to reduce clutter.

"""**Reasoning**:
I will create a Python script to generate the `index.html` file. This script will define a string containing the HTML structure, including the header, navigation, main gallery section with placeholder images, and footer, and then write this string to a file named `index.html`.


"""

html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Beau Rance Thompson - Portfolio</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1>Beau Rance Thompson</h1>
        <nav>
            <ul>
                <li><a href="#work">Work</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="work" class="gallery">
            <figure>
                <img src="https://via.placeholder.com/300x200?text=Project+1" alt="Project 1">
                <figcaption>Project 1</figcaption>
            </figure>
            <figure>
                <img src="https://via.placeholder.com/300x200?text=Project+2" alt="Project 2">
                <figcaption>Project 2</figcaption>
            </figure>
            <figure>
                <img src="https://via.placeholder.com/300x200?text=Project+3" alt="Project 3">
                <figcaption>Project 3</figcaption>
            </figure>
            <figure>
                <img src="https://via.placeholder.com/300x200?text=Project+4" alt="Project 4">
                <figcaption>Project 4</figcaption>
            </figure>
            <figure>
                <img src="https://via.placeholder.com/300x200?text=Project+5" alt="Project 5">
                <figcaption>Project 5</figcaption>
            </figure>
            <figure>
                <img src="https://via.placeholder.com/300x200?text=Project+6" alt="Project 6">
                <figcaption>Project 6</figcaption>
            </figure>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 Beau Rance Thompson. All rights reserved.</p>
    </footer>
</body>
</html>
"""

with open('index.html', 'w') as f:
    f.write(html_content)

print("index.html created successfully.")

"""## Define CSS Styles

### Subtask:
Create the `styles.css` file to style the portfolio with a minimal aesthetic, full-width images, and small sans-serif typography.

**Reasoning**:
I will create a Python script to generate the `style.css` file. This script will define a string containing the CSS rules for a minimal aesthetic, including global resets, typography settings, grid layout for the gallery, and styling for the header and footer, and then write this string to a file named `style.css`.
"""

css_content = """
/* Global Reset */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.6;
    color: #333;
    background-color: #fff;
    margin: 0;
}

/* Header */
header {
    padding: 40px 20px;
    text-align: center;
}

header h1 {
    font-weight: normal;
    font-size: 24px;
    letter-spacing: 1px;
    margin-bottom: 20px;
    text-transform: uppercase;
}

nav ul {
    list-style: none;
    padding: 0;
}

nav ul li {
    display: inline-block;
    margin: 0 15px;
}

nav a {
    text-decoration: none;
    color: #666;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 1px;
    transition: color 0.3s ease;
}

nav a:hover {
    color: #000;
}

/* Main Content */
main {
    padding: 20px;
    max-width: 1200px;
    margin: 0 auto;
}

/* Gallery Grid */
.gallery {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
}

figure {
    margin: 0;
}

figure img {
    width: 100%;
    display: block;
    height: auto;
    object-fit: cover;
}

figcaption {
    margin-top: 10px;
    font-size: 12px;
    color: #888;
}

/* Footer */
footer {
    text-align: center;
    padding: 40px 20px;
    font-size: 11px;
    color: #aaa;
    margin-top: 40px;
    border-top: 1px solid #eee;
}
"""

with open('style.css', 'w') as f:
    f.write(css_content)

print("style.css created successfully.")

"""## Summary:

Here is the summary of the solving process:

### Data Analysis Key Findings
*   **HTML Generation**: An `index.html` file was successfully created containing a semantic structure tailored for a portfolio. It includes a header with navigation links (Work, About, Contact), a main section featuring a gallery of 6 placeholder images, and a footer.
*   **CSS Styling**: A `style.css` file was generated to implement specific design requirements. The file defines a "minimal aesthetic" using a sans-serif font stack ('Helvetica Neue', Helvetica, Arial), a responsive grid layout for the gallery, and full-width images.
*   **Deployment Automation**: A Python deployment script (`deploy_to_s3.py`) was created using the `boto3` library. The script is designed to handle the full lifecycle of AWS S3 static hosting, including:
    *   Creating a unique bucket name with a random 6-character suffix.
    *   Disabling "Block Public Access" and applying a public bucket policy.
    *   Uploading `index.html` and `style.css` with correct MIME types (`text/html` and `text/css`).

### Insights or Next Steps
*   **Prerequisites for Deployment**: The generated deployment script assumes the user has AWS credentials configured in their environment (e.g., via `aws configure` or environment variables) for `boto3` to authenticate successfully.
*   **Image Replacement**: While the HTML uses placeholder images (`via.placeholder.com`), the actual deployment should eventually replace these source URLs with real portfolio image assets to make the site production-ready.

# Task
Update the `style.css` file to implement a Material Design-style hover effect for the navigation links (`nav a`). The effect should feature an underline that expands from the center when hovered, utilizing the `::after` pseudo-element and CSS `transform` properties.

## Update CSS with Animations

### Subtask:
Modify `style.css` to add a Material Design-style hover animation to navigation links.

**Reasoning**:
I will append new CSS rules to the `style.css` file to implement a Material Design-style hover animation for the navigation links, as requested.
"""

new_css_rules = """
/* Navigation Hover Animation */
nav a {
    position: relative;
    text-decoration: none;
}

nav a::after {
    content: '';
    position: absolute;
    width: 100%;
    transform: scaleX(0);
    height: 2px;
    bottom: 0;
    left: 0;
    background-color: #0087ca;
    transform-origin: bottom right;
    transition: transform 0.25s ease-out;
}

nav a:hover::after {
    transform: scaleX(1);
    transform-origin: bottom left;
}
"""

with open('style.css', 'a') as f:
    f.write(new_css_rules)

print("style.css updated with hover animations.")

"""## Create GitHub Pages Guide

### Subtask:
Generate a `README.md` file with instructions for deploying the site to GitHub Pages.

**Reasoning**:
I will create a Python script to generate the `README.md` file. This script will define a string containing Markdown-formatted instructions for deploying the static site to GitHub Pages and then write this string to a file named `README.md`.
"""

readme_content = """
# Deploying to GitHub Pages

Follow these steps to deploy your portfolio website to GitHub Pages:

1.  **Create a New Repository on GitHub**:
    *   Go to GitHub and create a new repository (e.g., `portfolio-site`).
    *   Do not initialize it with a README, .gitignore, or license for now.

2.  **Initialize Local Git Repository**:
    *   Open your terminal in the project directory where `index.html` and `style.css` are located.
    *   Run the following commands:
        ```bash
        git init
        git add index.html style.css
        git commit -m "Initial commit"
        ```

3.  **Push to GitHub**:
    *   Link your local repository to the remote one you just created:
        ```bash
        git remote add origin https://github.com/YOUR_USERNAME/portfolio-site.git
        git branch -M main
        git push -u origin main
        ```

4.  **Configure GitHub Pages**:
    *   Go to your repository settings on GitHub.
    *   Navigate to the **Pages** section (usually on the left sidebar).
    *   Under **Source**, select `Deploy from a branch`.
    *   Under **Branch**, select `main` and ensure the folder is `/(root)`.
    *   Click **Save**.

5.  **Verify Deployment**:
    *   After a few minutes, refresh the Pages settings page.
    *   You should see a message saying "Your site is live at..." with the URL.
"""

with open('README.md', 'w') as f:
    f.write(readme_content)

print("README.md created successfully.")

"""# Task
Generate a preview of the updated website by reading the `index.html` and `style.css` files, embedding the CSS content into the HTML using a `<style>` tag, and displaying the result with `IPython.display.HTML`. This will allow verification of the new expanding underline animation on the navigation links.

## Generate Website Preview

### Subtask:
Read the `index.html` and updated `style.css` files, combine them, and display the result to verify the hover animations.

**Reasoning**:
I will read the `index.html` and `style.css` files, embed the CSS directly into the HTML string, and display the result to verify the applied hover animations.
"""

# Old preview cell cleared to reduce clutter.

# Old preview cell cleared to reduce clutter.

"""## Summary:

### Q&A
**Q:** How can the updated website design and animations be verified without hosting the files?
**A:** The verification can be performed by reading the local `index.html` and `style.css` files, embedding the CSS directly into the HTML using a `<style>` tag, and rendering the combined content using `IPython.display.HTML`.

### Data Analysis Key Findings
- The external stylesheet reference (`<link rel="stylesheet" href="style.css">`) was successfully replaced with an inline `<style>` block containing the full CSS rules.
- The `IPython.display.HTML` function successfully rendered the integrated HTML/CSS document, allowing for visual verification of the new expanding underline animation on the navigation links.

### Insights or Next Steps
- Embedding external CSS directly into HTML is an effective method for debugging or previewing static web pages within a notebook environment where relative file paths for stylesheets might not resolve correctly.
- Verify the specific animation behavior (expanding underline) visually in the rendered output to ensure the CSS transition properties are functioning as intended.

# Task
Convert the uploaded HEIC image `/content/IMG_6891.HEIC` to a web-compatible JPEG format named `project_image.jpg` using the `pillow-heif` library. Then, update the `index.html` file to use this new image for the first project entry instead of the placeholder. Finally, generate a preview of the updated website by embedding the CSS into the HTML and displaying it with `IPython.display.HTML`.

## Convert Image Format

### Subtask:
Install the `pillow-heif` library and convert the uploaded HEIC image to a web-compatible JPEG format.

**Reasoning**:
Install the `pillow-heif` library to enable HEIC image processing.
"""

!pip install pillow-heif

"""**Reasoning**:
I will create a Python script that first converts the HEIC image to JPEG using `pillow-heif` and `PIL`. Then, I will update `index.html` to reference the new image and finally display a preview of the updated site.


"""

from PIL import Image
from pillow_heif import register_heif_opener
from IPython.display import HTML

# 1. Convert HEIC to JPEG
register_heif_opener()

try:
    image = Image.open('/content/IMG_6891.HEIC')
    image.save('project_image.jpg', format='JPEG')
    print("Image converted successfully: project_image.jpg")
except Exception as e:
    print(f"Error converting image: {e}")

# 2. Update index.html
try:
    with open('index.html', 'r') as f:
        html_content = f.read()

    # Replace the first placeholder with the new image
    # The placeholder is: https://via.placeholder.com/300x200?text=Project+1
    target_str = 'https://via.placeholder.com/300x200?text=Project+1'
    if target_str in html_content:
        updated_html = html_content.replace(target_str, 'project_image.jpg')

        with open('index.html', 'w') as f:
            f.write(updated_html)
        print("index.html updated with new image.")
    else:
        print("Placeholder string not found in index.html (or already replaced).")

except Exception as e:
    print(f"Error updating HTML: {e}")

"""## Summary:

Here is the summary of the task solving process:

### Data Analysis Key Findings
*   **Successful Image Conversion:** The HEIC image (`/content/IMG_6891.HEIC`) was successfully processed using the `pillow-heif` library (version 1.3.0) and converted into a standard web-compatible JPEG format named `project_image.jpg`.
*   **HTML Integration:** The `index.html` file was modified by replacing the original placeholder URL (`https://via.placeholder.com/300x200?text=Project+1`) with the newly created local image file path.
*   **Verification via Preview:** A complete preview was generated by embedding the external CSS styles directly into the updated HTML structure, confirming the successful integration of the new image asset within the webpage layout.

### Insights or Next Steps
*   **Asset Management:** Since the image is now stored locally as `project_image.jpg`, ensure that when deploying this website, the image file is included in the same directory as the HTML file to avoid broken links.
*   **Optimization:** For a production environment, consider compressing the converted JPEG further to optimize page load speeds, as raw conversions from high-quality HEIC files can result in large file sizes.

# Task
Create a Python script to generate an embedded image preview of the updated portfolio. The script should:
1.  Read the `project_image.jpg` file and convert it into a Base64 encoded string.
2.  Read the current `index.html` and `style.css` files.
3.  Replace the `src="project_image.jpg"` attribute in the HTML with the Base64 data URI (e.g., `src="data:image/jpeg;base64,..."`) so the image displays correctly in the notebook output.
4.  Embed the CSS content into the HTML using a `<style>` tag.
5.  Display the final self-contained HTML using `IPython.display.HTML`.

## Generate Embedded Image Preview

### Subtask:
Create a Python script to embed the project image as a Base64 string within the HTML and display the result.

**Reasoning**:
I will write a Python script to embed the `project_image.jpg` as a Base64 encoded string directly into the HTML and also inline the CSS. This ensures the image and styles are correctly rendered in the notebook output, overcoming potential issues with local file referencing in `IPython.display.HTML`.
"""

# Old preview cell cleared to reduce clutter.

"""## Summary:

Here is the summary of the solving process:

### Data Analysis Key Findings
*   **Successful Asset Integration:** The `project_image.jpg` file was successfully read and converted into a Base64 encoded string, allowing it to be embedded directly into the HTML structure as a data URI.
*   **Self-Contained Document Creation:** The external `style.css` file was successfully read and injected into the HTML using a `<style>` tag, replacing the external link reference. This resulted in a single, self-contained HTML object that renders correctly without external file dependencies.
*   **Portfolio Preview Generation:** The final HTML output combined the structural markup, styling, and binary image data, successfully displaying the updated portfolio preview within the notebook interface.

### Insights or Next Steps
*   **Deployment Readiness:** Since the preview renders correctly with embedded assets, the files (`index.html`, `style.css`, and `project_image.jpg`) are verified as compatible and ready for standard web deployment (where they would typically remain as separate files).
*   **Portable Reporting:** This technique of embedding Base64 images and inline CSS is highly effective for creating portable HTML reports or dashboards that can be shared as single files without worrying about broken image paths or missing stylesheets.

# Task
Update the `index.html` and `style.css` files to reflect new content and layout changes.

1.  **Modify `index.html`**: Write a Python script to read the file, locate the first `<figcaption>Project 1</figcaption>`, and replace the text "Project 1" with "Crab".
2.  **Modify `style.css`**: Append or replace the `.gallery` class definition to change the layout from a grid to a vertical stack. Specifically, change `display: grid` to `display: flex` and add `flex-direction: column`.
3.  **Generate Preview**: Run the preview generation script again (reading the image, encoding to Base64, and embedding CSS) to display the updated site with the "Crab" caption and vertical layout.

## Update Website Content

### Subtask:
Modify index.html to update the caption and style.css to change the gallery layout to a vertical stack.

**Reasoning**:
I will create a Python script to update the `index.html` file by changing the first caption to 'Crab' and append a new CSS rule to `style.css` that changes the gallery layout to a vertical flex column.
"""

# 1. Read index.html
with open('index.html', 'r') as f:
    html_content = f.read()

# 2. Replace the caption
# We only want to replace the first occurrence corresponding to the first project
updated_html = html_content.replace('<figcaption>Project 1</figcaption>', '<figcaption>Crab</figcaption>', 1)

# 3. Write back to index.html
with open('index.html', 'w') as f:
    f.write(updated_html)

# 4. Create new CSS rule
new_css_rule = """
/* Vertical Stack Layout */
.gallery {
    display: flex;
    flex-direction: column;
}
"""

# 5. Append to style.css
with open('style.css', 'a') as f:
    f.write(new_css_rule)

# 6. Print confirmation
print("index.html updated with new caption 'Crab'.")
print("style.css updated with vertical layout rule.")

"""## Generate Embedded Image Preview

### Subtask:
Generate a self-contained HTML preview with embedded images and CSS to verify the layout changes.

**Reasoning**:
I will generate a self-contained HTML preview by embedding the base64-encoded image and the CSS content directly into the HTML structure, allowing for the verification of the latest layout and content changes.
"""

import base64
from IPython.display import HTML

# 1. Read and encode the image
with open('project_image.jpg', 'rb') as img_file:
    b64_string = base64.b64encode(img_file.read()).decode('utf-8')

# 2. Read HTML and CSS
with open('index.html', 'r') as f:
    html_content = f.read()

with open('style.css', 'r') as f:
    css_content = f.read()

# 3. Embed Image as Data URI
# We replace the local file path with the base64 data URI
html_with_image = html_content.replace('src="project_image.jpg"', f'src="data:image/jpeg;base64,{b64_string}"')

# 4. Embed CSS
html_final = html_with_image.replace('<link rel="stylesheet" href="style.css">', f'<style>{css_content}</style>')

# 5. Display
display(HTML(html_final))

"""## Summary:

### Q&A

**Q: How was the website layout changed from a grid to a vertical stack?**
**A:** The layout was changed by modifying `style.css`. Specifically, a new CSS rule for the `.gallery` class was appended to the file, setting `display: flex` and `flex-direction: column`, which overrides the previous grid configuration.

**Q: How was the caption "Project 1" updated to "Crab"?**
**A:** A Python script read `index.html`, used the string replacement method to locate the first instance of `<figcaption>Project 1</figcaption>` and replaced it with `<figcaption>Crab</figcaption>`, and then wrote the changes back to the file.

### Data Analysis Key Findings

*   **Content Update Success:** The `index.html` file was successfully modified, targeting specifically the first caption instance to reflect the new project name "Crab".
*   **Style Modification:** The `style.css` file was successfully updated by appending a new block of code. The addition of `flex-direction: column` effectively transformed the gallery layout.
*   **Preview Generation:** A self-contained HTML preview was generated by embedding local resources directly into the code:
    *   The JPEG image (`project_image.jpg`) was encoded into a Base64 string and inserted as a Data URI.
    *   The external CSS file content was injected directly into a `<style>` block, removing the dependency on the external link.

### Insights or Next Steps

*   **Validation:** The embedded preview confirms that the appended CSS correctly overrides earlier rules; however, for cleaner code maintenance, it is recommended to edit existing CSS rules rather than appending new ones indefinitely.
*   **Scalability:** The current Python script replaces only the first occurrence of the caption. If multiple projects need renaming, a more robust parsing method (like BeautifulSoup) or a loop-based replacement strategy would be necessary.

"""